[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployments/"}]
optimizer = true
optimizer_runs = 2_000
solc = "0.8.20"
evm_version = "shanghai"
bytecode_hash = "none"

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }