[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@tangible/=lib/tnftv2-audit/contracts/",
    "@layerZero/=lib/LayerZero/",
    "@tangible-foundation-contracts/=lib/tangible-foundation-contracts/src/"
]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }